[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_ENV = "production"
  NODE_VERSION = "18"
  REACT_APP_API_BASE_URL = "https://api.esportspulse.com"
  REACT_APP_SOCKET_URL = "https://api.esportspulse.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 