// Otomatik oluşturulmuş logo mapping
export const teamLogos: Record<string, any> = {
  '100thieves': require('./100thieves.png'),
  '100_thieves': require('./100_Thieves.png'),
  '2gameesports': require('./2gameesports.png'),
  '2game_esports': require('./2Game_Esports.png'),
  '3blesports': require('./3blesports.png'),
  '3bl_esports': require('./3BL_Esports.png'),
  '9zteam': require('./9zteam.png'),
  '9z_team': require('./9z_Team.png'),
  'ab3esports': require('./ab3esports.png'),
  'ab3_esports': require('./AB3_Esports.png'),
  'alqadsiahesports': require('./alqadsiahesports.png'),
  'alqadsiah_esports': require('./AlQadsiah_Esports.png'),
  'alterego': require('./alterego.png'),
  'ambrosia': require('./ambrosia.png'),
  'bblesports': require('./bblesports.png'),
  'bblpcific': require('./bblpcific.png'),
  'bbl_esports': require('./BBL_Esports.png'),
  'bbl_pcific': require('./BBL_PCIFIC.png'),
  'bcswell': require('./bcswell.png'),
  'bc_swell': require('./BC_SWELL.png'),
  'bilibiligaming': require('./bilibiligaming.png'),
  'bilibili_gaming': require('./Bilibili_Gaming.png'),
  'blatersouthkorea': require('./blatersouthkorea.png'),
  'boboaustralia': require('./boboaustralia.png'),
  'boomesports': require('./boomesports.png'),
  'boom_esports': require('./BOOM_Esports.png'),
  'burgerboyz': require('./burgerboyz.png'),
  'burger_boyz': require('./Burger_Boyz.png'),
  'cgnesports': require('./cgnesports.png'),
  'cgn_esports': require('./CGN_Esports.png'),
  "chet's_pets": require("./Chet's_Pets.png"),
  'chetspets': require('./chetspets.png'),
  'chets_pets': require('./Chets_Pets.png'),
  'chet_s_pets': require('./chet_s_pets.png'),
  'chosencliquegaming': require('./chosencliquegaming.png'),
  'chosen_clique_gaming': require('./Chosen_Clique_Gaming.png'),
  'cloud9': require('./cloud9.png'),
  'cnjesports': require('./cnjesports.png'),
  'cnj_esports': require('./CNJ_Esports.png'),
  'corinthiansesports': require('./corinthiansesports.png'),
  'corinthians_esports': require('./Corinthians_Esports.png'),
  'cumberlandphoenix': require('./cumberlandphoenix.png'),
  'cumberland_phoenix': require('./Cumberland_Phoenix.png'),
  'default': require('./default.png'),
  // ... diğer logolar ...
}; 